appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: hGvVp0KHwCcN+MlWzIzQN8w5x0RIYgLyMoZxPeddU65Akmb+Kv0qqgtiyVl5625+qHmtt3hSKZ8DKauKg7oQuXV7aogNeUKcDvinYQptkh6iaGjeE9FA048zUMvu/DpzC9vCcWxT5iirLdVsAgmqW/NMPEIkxvd0gWy6Pq26mN2d9oBop0XZvWS0FYPnA0d5O2J+Ia+hAmhdLV09oLSM3uImoVu1Rq+ELk0rcPVjq+OUZ52fQQ8e+PqgqWmwD/0ArOKWtfiFoJzzNyfe/Dtvay2SZnV5dkzAei4iH1UBpIV+81Hy4imVzxkLFOBC02keZCpy9IA8sJkXihCL8bh2ab34mZ1uusYQC+dqzJz0WNSDTzERqQ/FX+4H+7HKcJYlmCClDKPb4KFue8p3ubgIQI7xWlEaObGWBofcTKshlRQpcqTXwuVu8WeWYI8nwh4QWzXD80g8NvpGs+NhJVcqOr8jnujSEAbtl+0aitAM6Ag5gIUjFELVpaZq883+YXzH7P6s9UBa4P5Yblb+Q3Q16pKW8q1IXquOJR7ns3CaWPq8HsdiDKCUCkI3kc0wxG+z3PXnTy6Q0edMr8hX9tFZTwagXu13oEc6s/PWsC/cXkUUKH8AN1dtVN9UKIm1PDME5NCQrhUasTBTzrqDWWax+IrvhrtTn5AmGirkFF8a5BM=
conda_forge_output_validation: false
